In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import numpy as np 
import pandas as pd 
import os
import glob
import time
import pandas as pd

from nltk import ngrams
from nltk.tokenize import sent_tokenize
import nltk
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
from nltk.stem import PorterStemmer
from nltk.stem import PorterStemmer
from nltk.tokenize import sent_tokenize, word_tokenize
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords 
from nltk.tokenize import word_tokenize

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.


In [3]:
from google.colab import files

df = pd.read_csv("/content/drive/MyDrive/sqli.csv",encoding='utf-16')
df

Sentence  Label
0                                                     a      1
1                                                   a'       1
2                                                 a' --      1
3                                       a' or 1 = 1; --      1
4                                                     @      1
...                                                 ...    ...
4195   org/?option = com_k2  <a href = "http://corfopym      0
4196  com/?option = com_k2  <act>  <![CDATA[procMemb...      0
4197                                          picsearch      0
4198  com/is?-WZx-uhyLezKNiYLvAbKL3W4oh5F749nr2KUmFF...      0
4199  de]]>  </email_address>   <find_account_answer...      0

[4200 rows x 2 columns]

In [4]:
df['Label'].value_counts()

0    3072
1    1128
Name: Label, dtype: int64

In [5]:

from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer( min_df=2, max_df=0.7, stop_words=stopwords.words('english'))
posts = vectorizer.fit_transform(df['Sentence'].values.astype('U')).toarray()



In [6]:
posts

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0]])

In [7]:
transformed_posts=pd.DataFrame(posts)
transformed_posts.head(10)

0     1     2     3     4     5     6     7     8     9     ...  4707  \
0     0     0     0     0     0     0     0     0     0     0  ...     0   
1     0     0     0     0     0     0     0     0     0     0  ...     0   
2     0     0     0     0     0     0     0     0     0     0  ...     0   
3     0     0     0     0     0     0     0     0     0     0  ...     0   
4     0     0     0     0     0     0     0     0     0     0  ...     0   
5     0     0     0     0     0     0     0     0     0     0  ...     0   
6     0     0     0     0     0     0     0     0     0     0  ...     0   
7     0     0     0     0     0     0     0     0     0     0  ...     0   
8     0     0     0     0     0     0     0     0     0     0  ...     0   
9     0     0     0     0     0     0     0     0     0     0  ...     0   

   4708  4709  4710  4711  4712  4713  4714  4715  4716  
0     0     0     0     0     0     0     0     0     0  
1     0     0     0     0     0     0     0     0     0  
2     0     0     0     0     0     0     0     0     0  
3     0     0     0     0     0     0     0     0     0  
4     0     0     0     0     0     0     0     0     0  
5     0     0     0     0     0     0     0     0     0  
6     0     0     0     0     0     0     0     0     0  
7     0     0     0     0     0     0     0     0     0  
8     0     0     0     0     0     0     0     0     0  
9     0     0     0     0     0     0     0     0     0  

[10 rows x 4717 columns]

In [8]:
df=pd.concat([df,transformed_posts],axis=1)
df.head(10)

Sentence  Label  0  1  2  3  4  5  6  7  ...  4707  4708  \
0                          a      1  0  0  0  0  0  0  0  0  ...     0     0   
1                        a'       1  0  0  0  0  0  0  0  0  ...     0     0   
2                      a' --      1  0  0  0  0  0  0  0  0  ...     0     0   
3            a' or 1 = 1; --      1  0  0  0  0  0  0  0  0  ...     0     0   
4                          @      1  0  0  0  0  0  0  0  0  ...     0     0   
5                          ?      1  0  0  0  0  0  0  0  0  ...     0     0   
6   ' and 1 = 0 )  union all      1  0  0  0  0  0  0  0  0  ...     0     0   
7              ? or 1 = 1 --      1  0  0  0  0  0  0  0  0  ...     0     0   
8  x' and userid is NULL; --      1  0  0  0  0  0  0  0  0  ...     0     0   
9   x' and email is NULL; --      1  0  0  0  0  0  0  0  0  ...     0     0   

   4709  4710  4711  4712  4713  4714  4715  4716  
0     0     0     0     0     0     0     0     0  
1     0     0     0     0     0     0     0     0  
2     0     0     0     0     0     0     0     0  
3     0     0     0     0     0     0     0     0  
4     0     0     0     0     0     0     0     0  
5     0     0     0     0     0     0     0     0  
6     0     0     0     0     0     0     0     0  
7     0     0     0     0     0     0     0     0  
8     0     0     0     0     0     0     0     0  
9     0     0     0     0     0     0     0     0  

[10 rows x 4719 columns]

In [9]:
X=df[df.columns[2:]]

In [10]:
y=df['Label']

In [11]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
X.head()

0     1     2     3     4     5     6     7     8     9     ...  4707  \
0     0     0     0     0     0     0     0     0     0     0  ...     0   
1     0     0     0     0     0     0     0     0     0     0  ...     0   
2     0     0     0     0     0     0     0     0     0     0  ...     0   
3     0     0     0     0     0     0     0     0     0     0  ...     0   
4     0     0     0     0     0     0     0     0     0     0  ...     0   

   4708  4709  4710  4711  4712  4713  4714  4715  4716  
0     0     0     0     0     0     0     0     0     0  
1     0     0     0     0     0     0     0     0     0  
2     0     0     0     0     0     0     0     0     0  
3     0     0     0     0     0     0     0     0     0  
4     0     0     0     0     0     0     0     0     0  

[5 rows x 4717 columns]

In [ ]:
#Logistic Reegression   

In [ ]:
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(random_state=0).fit(X_train, y_train)
from sklearn.metrics import accuracy_score
y_pred=clf.predict(X_test)
accuracy_score(y_test, y_pred)

0.9285714285714286

In [ ]:
# Naive Bayes

In [ ]:
from sklearn.naive_bayes import GaussianNB

gnb = GaussianNB()

gnb.fit(X_train, y_train)

pred_gnb = gnb.predict(X_test)

In [ ]:
# SVM
from sklearn.svm import SVC
clf = SVC(gamma='auto')
clf.fit(X_train, y_train)
pred_svm=clf.predict(X_test)

In [ ]:
# KNN
from sklearn.neighbors import KNeighborsClassifier

neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(X_train, y_train)

pred_knn = neigh.predict(X_test)

In [ ]:
# DT
from sklearn import tree

dt = tree.DecisionTreeClassifier()
dt = dt.fit(X_train, y_train)

pred_dt = dt.predict(X_test)

In [ ]:
def accuracy_function(tp,tn,fp,fn):
    
    accuracy = (tp+tn) / (tp+tn+fp+fn)
    
    return accuracy

def precision_function(tp,fp):
    
    precision = tp / (tp+fp)
    
    return precision

def recall_function(tp,fn):
    
    recall=tp / (tp+fn)
    
    return recall

def confusion_matrix(truth,predicted):
    
    true_positive = 0
    true_negative = 0
    false_positive = 0
    false_negative = 0
    
    for true,pred in zip(truth,predicted):
        
        if true == 1:
            if pred == true:
                true_positive += 1
            elif pred != true:
                false_negative += 1

        elif true == 0:
            if pred == true:
                true_negative += 1
            elif pred != true:
                false_positive += 1
            
    accuracy = accuracy_function(true_positive, true_negative, false_positive, false_negative)
    precision = precision_function(true_positive, false_positive)
    recall = recall_function(true_positive, false_negative)
    
    return (accuracy,precision,recall)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print("For Logistic Regression\n\n")
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

For Logistic Regression


[[585   3]
 [ 57 195]]
              precision    recall  f1-score   support

           0       0.91      0.99      0.95       588
           1       0.98      0.77      0.87       252

    accuracy                           0.93       840
   macro avg       0.95      0.88      0.91       840
weighted avg       0.93      0.93      0.93       840

0.9285714285714286


In [ ]:
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("For Logistic Regression")
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
print("Precision:",metrics.precision_score(y_test, y_pred))
print("Recall:",metrics.recall_score(y_test, y_pred))

For Logistic Regression
Accuracy: 0.9285714285714286
Precision: 0.9848484848484849
Recall: 0.7738095238095238


In [ ]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print("For Gaussian Naive Bayes\n\n")
print(confusion_matrix(y_test, pred_gnb))
print(classification_report(y_test, pred_gnb))
print(accuracy_score(y_test, pred_gnb))

For Gaussian Naive Bayes


[[569  19]
 [  0 252]]
              precision    recall  f1-score   support

           0       1.00      0.97      0.98       588
           1       0.93      1.00      0.96       252

    accuracy                           0.98       840
   macro avg       0.96      0.98      0.97       840
weighted avg       0.98      0.98      0.98       840

0.9773809523809524


In [ ]:
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("For Naive Bayes")
print("Accuracy:",metrics.accuracy_score(y_test, pred_gnb))
print("Precision:",metrics.precision_score(y_test, pred_gnb))
print("Recall:",metrics.recall_score(y_test, pred_gnb))

For Naive Bayes
Accuracy: 0.9773809523809524
Precision: 0.9298892988929889
Recall: 1.0


In [ ]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print("For Support Vector Machine\n\n")
print(confusion_matrix(y_test, pred_svm))
print(classification_report(y_test, pred_svm))
print(accuracy_score(y_test, pred_svm))

For Support Vector Machine


[[588   0]
 [198  54]]
              precision    recall  f1-score   support

           0       0.75      1.00      0.86       588
           1       1.00      0.21      0.35       252

    accuracy                           0.76       840
   macro avg       0.87      0.61      0.60       840
weighted avg       0.82      0.76      0.71       840

0.7642857142857142


In [ ]:
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("For Support Vecctor Machine")
print("Accuracy:",metrics.accuracy_score(y_test, pred_svm))
print("Precision:",metrics.precision_score(y_test, pred_svm))
print("Recall:",metrics.recall_score(y_test, pred_svm))

For Support Vecctor Machine
Accuracy: 0.7642857142857142
Precision: 1.0
Recall: 0.21428571428571427


In [ ]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print("For K- Nearest Neighbor\n\n")
print(confusion_matrix(y_test, pred_knn))
print(classification_report(y_test, pred_knn))
print(accuracy_score(y_test, pred_knn))

For K- Nearest Neighbor


[[225 363]
 [  0 252]]
              precision    recall  f1-score   support

           0       1.00      0.38      0.55       588
           1       0.41      1.00      0.58       252

    accuracy                           0.57       840
   macro avg       0.70      0.69      0.57       840
weighted avg       0.82      0.57      0.56       840

0.5678571428571428


In [ ]:
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("For K- Nearest Neighbor")
print("Accuracy:",metrics.accuracy_score(y_test, pred_knn))
print("Precision:",metrics.precision_score(y_test, pred_knn))
print("Recall:",metrics.recall_score(y_test, pred_knn))

For K- Nearest Neighbor
Accuracy: 0.5678571428571428
Precision: 0.4097560975609756
Recall: 1.0


In [ ]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print("For Decision Tree\n\n")
print(confusion_matrix(y_test, pred_dt))
print(classification_report(y_test, pred_dt))
print(accuracy_score(y_test, pred_dt))

For Decision Tree


[[477 111]
 [  0 252]]
              precision    recall  f1-score   support

           0       1.00      0.81      0.90       588
           1       0.69      1.00      0.82       252

    accuracy                           0.87       840
   macro avg       0.85      0.91      0.86       840
weighted avg       0.91      0.87      0.87       840

0.8678571428571429


In [ ]:
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("For Decision Tree")
print("Accuracy:",metrics.accuracy_score(y_test, pred_dt))
print("Precision:",metrics.precision_score(y_test, pred_dt))
print("Recall:",metrics.recall_score(y_test, pred_dt))

For Decision Tree
Accuracy: 0.8678571428571429
Precision: 0.6942148760330579
Recall: 1.0


In [ ]:
from keras.models import Sequential
from keras import layers
from keras.preprocessing.text import Tokenizer
from keras.wrappers.scikit_learn import KerasClassifier

In [ ]:
input_dim = X_train.shape[1]  # Number of features

model = Sequential()
model.add(layers.Dense(20, input_dim=input_dim, activation='relu'))
model.add(layers.Dense(10,  activation='tanh'))
model.add(layers.Dense(1024, activation='relu'))

model.add(layers.BatchNormalization())
model.add(layers.Dropout(0.6))
model.add(layers.Dense(1, activation='sigmoid'))

In [ ]:
model.compile(loss='binary_crossentropy', 
              optimizer='adam', 
              metrics=['accuracy'])
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 20)                94360     
                                                                 
 dense_1 (Dense)             (None, 10)                210       
                                                                 
 dense_2 (Dense)             (None, 1024)              11264     
                                                                 
 batch_normalization (BatchN  (None, 1024)             4096      
 ormalization)                                                   
                                                                 
 dropout (Dropout)           (None, 1024)              0         
                                                                 
 dense_3 (Dense)             (None, 1)                 1025      
                                                        

In [ ]:
classifier_nn = model.fit(X_train,y_train,
                    epochs=20,
                    verbose=True,
                    validation_data=(X_test, y_test),
                    batch_size=15)

Epoch 1/20
224/224 [==============================] - 1s 5ms/step - loss: 0.0694 - accuracy: 0.9765 - val_loss: 0.0843 - val_accuracy: 0.9679
Epoch 2/20
224/224 [==============================] - 1s 5ms/step - loss: 0.0620 - accuracy: 0.9774 - val_loss: 0.0764 - val_accuracy: 0.9726
Epoch 3/20
224/224 [==============================] - 1s 4ms/step - loss: 0.0655 - accuracy: 0.9735 - val_loss: 0.0961 - val_accuracy: 0.9631
Epoch 4/20
224/224 [==============================] - 1s 4ms/step - loss: 0.0727 - accuracy: 0.9750 - val_loss: 0.0836 - val_accuracy: 0.9702
Epoch 5/20
224/224 [==============================] - 1s 4ms/step - loss: 0.0745 - accuracy: 0.9756 - val_loss: 0.1333 - val_accuracy: 0.9571
Epoch 6/20
224/224 [==============================] - 1s 4ms/step - loss: 0.0669 - accuracy: 0.9753 - val_loss: 0.1007 - val_accuracy: 0.9643
Epoch 7/20
224/224 [==============================] - 1s 4ms/step - loss: 0.0614 - accuracy: 0.9768 - val_loss: 0.0761 - val_accuracy: 0.9714
Epoch 

In [ ]:
pred=model.predict(X_test)

In [ ]:
for i in range(len(pred)):
    if pred[i]>0.5:
        pred[i]=1
    elif pred[i]<=0.5:
        pred[i]=0

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print("For CNN Tree\n\n")
print(confusion_matrix(y_test, pred))
print(classification_report(y_test, pred))
print(accuracy_score(y_test, pred))

For CNN Tree


[[566  22]
 [  0 252]]
              precision    recall  f1-score   support

           0       1.00      0.96      0.98       588
           1       0.92      1.00      0.96       252

    accuracy                           0.97       840
   macro avg       0.96      0.98      0.97       840
weighted avg       0.98      0.97      0.97       840

0.9738095238095238


In [ ]:
from sklearn import metrics
print("For CNN")
print("Accuracy:",metrics.accuracy_score(y_test, pred))
print("Precision:",metrics.precision_score(y_test, pred))
print("Recall:",metrics.recall_score(y_test, pred))

For CNN
Accuracy: 0.9738095238095238
Precision: 0.9197080291970803
Recall: 1.0


In [ ]:
from keras.models import load_model
import pickle

model.save('my_model_cnn.h5')
with open('vectorizer_cnn', 'wb') as fin:
    pickle.dump(vectorizer, fin)


In [ ]:
import keras
from keras.models import load_model
import pickle
import tensorflow as tf


mymodel = tf.keras.models.load_model('my_model_cnn.h5')
myvectorizer = pickle.load(open("vectorizer_cnn", 'rb'))




def clean_data(input_val):

    input_val=input_val.replace('\n', '')
    input_val=input_val.replace('%20', ' ')
    input_val=input_val.replace('=', ' = ')
    input_val=input_val.replace('((', ' (( ')
    input_val=input_val.replace('))', ' )) ')
    input_val=input_val.replace('(', ' ( ')
    input_val=input_val.replace(')', ' ) ')
    input_val=input_val.replace('1 ', 'numeric')
    input_val=input_val.replace(' 1', 'numeric')
    input_val=input_val.replace("'1 ", "'numeric ")
    input_val=input_val.replace(" 1'", " numeric'")
    input_val=input_val.replace('1,', 'numeric,')
    input_val=input_val.replace(" 2 ", " numeric ")
    input_val=input_val.replace(' 3 ', ' numeric ')
    input_val=input_val.replace(' 3--', ' numeric--')
    input_val=input_val.replace(" 4 ", ' numeric ')
    input_val=input_val.replace(" 5 ", ' numeric ')
    input_val=input_val.replace(' 6 ', ' numeric ')
    input_val=input_val.replace(" 7 ", ' numeric ')
    input_val=input_val.replace(" 8 ", ' numeric ')
    input_val=input_val.replace('1234', ' numeric ')
    input_val=input_val.replace("22", ' numeric ')
    input_val=input_val.replace(" 8 ", ' numeric ')
    input_val=input_val.replace(" 200 ", ' numeric ')
    input_val=input_val.replace("23 ", ' numeric ')
    input_val=input_val.replace('"1', '"numeric')
    input_val=input_val.replace('1"', '"numeric')
    input_val=input_val.replace("7659", 'numeric')
    input_val=input_val.replace(" 37 ", ' numeric ')
    input_val=input_val.replace(" 45 ", ' numeric ')

    return input_val








def predict_sqli_attack():
    
    repeat=True
    
    beautify=''
    for i in range(20):
        beautify+= "*"

    print(beautify) 
    input_val=input("Enter a sentence : ")


    
    if input_val== '0':
        repeat=False
    
    

    input_val=clean_data(input_val)
    input_val=[input_val]



    input_val=myvectorizer.transform(input_val).toarray()
    
   # input_val.shape=(1,64,64,1)

    result=mymodel.predict(input_val)


#     print(beautify
    
    
    if repeat == True:
        
        if result>0.5:
            print("ALERT!!!! SQL injection Detected")


        elif result<=0.5:
            print("It is normal")
            
        print(beautify)
            
        predict_sqli_attack()
            
    elif repeat == False:
        print( " Closing detection ")

 



In [ ]:
predict_sqli_attack()

********************
Enter a sentence : We have to finish our project on tme
It is normal
********************
********************
Enter a sentence : We have to finish our project on time
It is normal
********************
********************
Enter a sentence : select * from
ALERT!!!! SQL injection Detected
********************
********************
Enter a sentence : select *
ALERT!!!! SQL injection Detected
********************
********************
Enter a sentence : from data1 
ALERT!!!! SQL injection Detected
********************
********************
Enter a sentence : 0
 Closing detection 
